
----------dockerfile VersionWithWindows版，有指定port(有成功)----------
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
ENV ASPNETCORE_URLS=http://+:8081
WORKDIR /app
EXPOSE 8081/tcp
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "dockerWeb.dll"]
----------------------------------------

嘗試結果 => 無法載入nuget api 的json頁面(在公司)

----------dockerfile VersionWith成功----------
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "DockerTest.dll"]

----------------------------------------

